//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18047
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarkDownSharpEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarkDownSharpEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   You already have the latest version of this application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AlreadyLatestVersion {
            get {
                return ResourceManager.GetString("AlreadyLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find to &amp;Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonFindNext {
            get {
                return ResourceManager.GetString("ButtonFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find to &amp;Previous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonFindPrev {
            get {
                return ResourceManager.GetString("ButtonFindPrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace to &amp;Next に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonReplaceNext {
            get {
                return ResourceManager.GetString("ButtonReplaceNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Replace to &amp;Previous に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ButtonReplacePrev {
            get {
                return ResourceManager.GetString("ButtonReplacePrev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleInfo {
            get {
                return ResourceManager.GetString("DialogTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleNotice {
            get {
                return ResourceManager.GetString("DialogTitleNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Question に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DialogTitleQuestion {
            get {
                return ResourceManager.GetString("DialogTitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to get the latest version information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorGetNewVersion {
            get {
                return ResourceManager.GetString("ErrorGetNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Changed) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FlagChanged {
            get {
                return ResourceManager.GetString("FlagChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   More than one were read.\nDo you wish to convert all files to HTML files on this options?
        ///if you select &apos;No&apos;, all files will be opend without converting. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgConvertAllFilesToHTML {
            get {
                return ResourceManager.GetString("MsgConvertAllFilesToHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (Default) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgDefaultCSS {
            get {
                return ResourceManager.GetString("MsgDefaultCSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error during deleting temporary file!\na temporary file may be left in the folder the file is edited.
        ///This file is not a problem even if you delete it manually. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgErrorDeleteTemporaryFile {
            get {
                return ResourceManager.GetString("MsgErrorDeleteTemporaryFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searching completed to the beginning of this file.
        ///Do you wish to continue searching from the end of this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgFindCompleteToBegining {
            get {
                return ResourceManager.GetString("MsgFindCompleteToBegining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searching completed to the beginning of this file.
        ///Do you wish to continue searching from the end of this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgFindCompleteToBeginning {
            get {
                return ResourceManager.GetString("MsgFindCompleteToBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Searching completed to the end of this file.
        ///Do you wish to continue searching from the beginning of this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgFindCompleteToEnd {
            get {
                return ResourceManager.GetString("MsgFindCompleteToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you remove this file in list, and move to trash? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgMoveToTrash {
            get {
                return ResourceManager.GetString("MsgMoveToTrash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find Help file. Opening this file has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgNoHelpFile {
            get {
                return ResourceManager.GetString("MsgNoHelpFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find sample MD file.\nOpening this file has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgNoSampleFile {
            get {
                return ResourceManager.GetString("MsgNoSampleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The word was not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgNotFound {
            get {
                return ResourceManager.GetString("MsgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Association tool is not found, therefore failed to associate .md files with this application. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgNotFoundAssociationTool {
            get {
                return ResourceManager.GetString("MsgNotFoundAssociationTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The word could not find to the beginning of this file.
        ///Do you wish to continue searching from the end of this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgNotFoundToBegining {
            get {
                return ResourceManager.GetString("MsgNotFoundToBegining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The word could not find to the beginning of this file.
        ///Do you wish to continue searching from the end of this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgNotFoundToBeginning {
            get {
                return ResourceManager.GetString("MsgNotFoundToBeginning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The word could not find the word to the end of this file.
        ///Do you wish to continue searching from the beginning of this file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgNotFoundToEnd {
            get {
                return ResourceManager.GetString("MsgNotFoundToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file has been output to the clipboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgOutputToClipboard {
            get {
                return ResourceManager.GetString("MsgOutputToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///    of the word were replaced. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgReplaced {
            get {
                return ResourceManager.GetString("MsgReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   To change the setting of language, it is necessary to restart the application.
        ///Do you want to restart this application now? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgRestartApplication {
            get {
                return ResourceManager.GetString("MsgRestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Same CSS file exitsts already. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgSameCSSFileExists {
            get {
                return ResourceManager.GetString("MsgSameCSSFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Same file exists.\nContinue to overwrite? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgSameFileOverwrite {
            get {
                return ResourceManager.GetString("MsgSameFileOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file being edited. Do you wish to save before exiting? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgSaveFileToEnd {
            get {
                return ResourceManager.GetString("MsgSaveFileToEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file being edited. Do you wish to save before starting new file? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgSaveFileToNewFile {
            get {
                return ResourceManager.GetString("MsgSaveFileToNewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   These CSS files is found. Do you add these files to list? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgTheseCSSFilesFound {
            get {
                return ResourceManager.GetString("MsgTheseCSSFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MsgThisWord {
            get {
                return ResourceManager.GetString("MsgThisWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New version was found! Do you open the download site? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewVersionFound {
            get {
                return ResourceManager.GetString("NewVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (No title) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NoFileName {
            get {
                return ResourceManager.GetString("NoFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No CSS file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string toolTipCssFileName {
            get {
                return ResourceManager.GetString("toolTipCssFileName", resourceCulture);
            }
        }
    }
}
